Vis delvilkår er automatisk beregnet
navikt/familie-ef-sak-frontend pull request #1412
Opened 2022-07-18 19:53 UTC by olekvernberg

2022-07-19 05:34 UTC, charliemidtlyng commented on src/frontend/Komponenter/Behandling/Vurdering/VisVurdering.tsx
> +    const erAutomatiskVurdert = vurdering.delvilkårsvurderinger.every(
Vil disse vilkårene vises med svar nå? 
`vurderingerBesvaradeAvSaksbehandler` filtrere de som er `OPPFYLT` og `IKKE_OPPFYLT` og viser  vel bare svarene til disse? Tror kanskje vi må få inn de som er automatisk oppfylt i den lista også?

2022-07-19 05:35 UTC, charliemidtlyng commented on src/frontend/Komponenter/Behandling/Vurdering/VisVurdering.tsx
> +    const erAutomatiskVurdert = vurdering.delvilkårsvurderinger.every(
Se linje 89/90

2022-07-20 13:03 UTC, olekvernberg commented on src/frontend/Komponenter/Behandling/Vurdering/VisVurdering.tsx
> +    const erAutomatiskVurdert = vurdering.delvilkårsvurderinger.every(
Hvis jeg har skjønt det rett, så vises svarene. Slik ser det ut:
<img width="746" alt="Screen Shot 2022-07-20 at 15 01 26" src="https://user-images.githubusercontent.com/42737566/179988506-7465d43b-a6f1-466a-98bd-f190e941db72.png">
<img width="1236" alt="Screen Shot 2022-07-20 at 15 02 26" src="https://user-images.githubusercontent.com/42737566/179988620-34c413bd-71f4-4104-9a02-ce151527bcd0.png">

2022-07-20 13:07 UTC, olekvernberg commented on src/frontend/Komponenter/Behandling/Vurdering/VisVurdering.tsx
> +    const erAutomatiskVurdert = vurdering.delvilkårsvurderinger.every(
Skjønner ikke helt hvorfor den ikke trengs der. Vi kan kanskje ta en rask test sammen preprod, før jeg gir det over til Mirja, en gang i løpet av morgendagen :)

2022-07-21 07:36 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/Vurdering/VisVurdering.tsx
> +    const erAutomatiskVurdert = vurdering.delvilkårsvurderinger.every(
Vurderingene som er lagt inn i `vurderingerBesvaradeAvSaksbehandler` viser alle delvilkårsvurderingene til vilkårene i denne listen. Såvidt jeg kan se bør også vilkår som er `AUTOMATISK_OPPFYLT` tas med i listen også. Da skal det se slik ut:
(bare med (automatisk i overskriften og sannsynligvis en annen begrunnelse)

![Skjermbilde 2022-07-21 kl  09 36 14](https://user-images.githubusercontent.com/32769446/180156929-bd684fc9-ff19-41ee-a9db-3c63d2616876.png)

2022-07-21 07:37 UTC, ViktorGSolberg requested changes
se kommentar

2022-07-21 08:55 UTC, ViktorGSolberg approved these changes

2022-07-21 11:50 UTC, merged