Skal ikke hente bereging/beløpsperioder dersom resultat er sanksjon
navikt/familie-ef-sak-frontend pull request #1906
Opened 2023-01-02 09:54 UTC by eirarset

https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10031

2023-01-02 09:57 UTC, blommish approved these changes

2023-01-02 09:57 UTC, blommish commented on src/frontend/Komponenter/Behandling/Brev/Brevmeny.tsx
> +            hentBeløpsperioder(vedtaksresultat);
Burde kanskej ha med curly brackets? 
```suggestion
        if (vedtaksresultat !== EBehandlingResultat.SANKSJONERE) {
            hentBeløpsperioder(vedtaksresultat);
        }
```

2023-01-02 10:03 UTC, eirarset commented on src/frontend/Komponenter/Behandling/Brev/Brevmeny.tsx
> +            hentBeløpsperioder(vedtaksresultat);
Ups

2023-01-02 13:58 UTC, charliemidtlyng approved these changes

2023-01-02 14:00 UTC, charliemidtlyng commented
Hvordan blir datavieweren nå, egentlig? Kommer det noen gang noen valgmuligheter når vi ikke henter beløpsperiodene? 🤔 
```
                <DataViewer
                    response={{
                        brevStruktur,
                        mellomlagretBrev,
                        beløpsperioder,
                    }}
```

2023-01-05 21:56 UTC, charliemidtlyng requested changes
Denne bør nok heller løses i backend - slik at vi faktisk henter riktige verdier også for barnetilsyn med sanksjon.

2023-01-06 08:25 UTC, eirarset commented
> Denne bør nok heller løses i backend - slik at vi faktisk henter riktige verdier også for barnetilsyn med sanksjon.

Enig, lukker denne.

2023-01-06 08:25 UTC, closed without merging