Historikk i tidligere vedtaksperioder
navikt/familie-ef-sak-frontend pull request #2522
Opened 2023-09-11 10:31 UTC by gunnsteingarmo

### Hvorfor er denne endringen nødvendig? ✨
Ønsker å vise frem historikk i tidligerevedtaksperioder, har derfor laget komponenter som kan brukes til dette.

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12418

![image](https://github.com/navikt/familie-ef-sak-frontend/assets/141132903/23815a92-0f51-4218-bebe-2ab2edf7cbf3)

2023-09-11 11:13 UTC, ViktorGSolberg commented
![Skjermbilde 2023-09-11 kl  13 11 23](https://github.com/navikt/familie-ef-sak-frontend/assets/32769446/2d19e677-f58f-4c9a-88b8-7d88f048c7bf)
 
 Fikk denne feilen når jeg testet lokalt

2023-09-21 11:28 UTC, charliemidtlyng commented
Generelt vil jeg fraråde bruk av `...` som commit-melding. 
Skriv hva du ønsker å oppnå med en commit-melding. Om det er formatering av kode, fiks feil i kompilering eller annet smårusk så skriv gjerne det - for `...` blir litt magisk og gir ikke noe kontekst til senere.

2023-09-21 11:33 UTC, charliemidtlyng commented on src/frontend/Komponenter/Behandling/Tabell/TabellVisningMedTag.tsx
> +                        {renderTag(stonad.verdier?.verdi[0].sak)}
Litt magi - kunne 
`<td>${harHistorikkEfSak ? <TagJa /> : <TagNei /></td>`

være et mer lesbart alternativ? Så kan <TagJa> og <TagNei> defineres på toppen ?

2023-09-21 11:34 UTC, charliemidtlyng commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/OSHistorikKort.tsx
> +                    {sak?.periodeHistorikkOvergangsstønad?.length > 0 ? (
Burde ikke trenge `sak?.` her?

2023-09-21 11:35 UTC, charliemidtlyng commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/OSHistorikKort.tsx
> +                                </Row>
Kan dette dras ut til 
`<HistorikkRad rad={rad} key={i} />`

2023-09-21 11:43 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/typer.ts
> +    antallMndUtenBeløp: number;
```suggestion
    antallMåneder: number;
    antallMånederUtenBeløp: number;
```

Vi har pleid å skrive disse ordene helt ut ellers i løsningen

2023-09-21 11:46 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/TidligereVedtaksperiodeKort.tsx
> +                    {/* <pre>{JSON.stringify(stonad, null, 2)}</pre> */}
```suggestion

```
Fjern denne

2023-09-21 11:48 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/TidligereVedtaksperioderInfo.tsx
> +                {mapIkon(VilkårInfoIkon.REGISTER)}
```suggestion
<Registergrunnlag />
```

Her ville jeg bare brukt ikonet direkte. Det er jo ingenting som skal endre seg

2023-09-21 11:51 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/TidligereVedtaksperioderInfo.tsx
> +                        tidligereVedtaksperioder.historiskPensjon ? 'success-filled' : 'neutral'
```suggestion
                        tagVariant
```
Selv liker jeg å utlede slike verdier øverst i komponenten før return statementet. Da blir komponentens innhold ofte lettere å lese. 

`const tagVariant = tidligereVedtaksperioder.historiskPensjon ? 'success-filled' : 'neutral';` kan plasseres lenger oppe altså

2023-09-25 07:49 UTC, gunnsteingarmo commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/OSHistorikKort.tsx
> +                                </Row>
Godt poeng, har gjort det nå.

2023-09-25 07:50 UTC, gunnsteingarmo commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/TidligereVedtaksperioderInfo.tsx
> +                        tidligereVedtaksperioder.historiskPensjon ? 'success-filled' : 'neutral'
Enig med deg, har gjort endringer.

2023-09-25 07:53 UTC, gunnsteingarmo commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/TidligereVedtaksperiodeKort.tsx
> +        </Container>
Har gjort endringer, men mapper fremdeles. Det er fordi jeg har laget laget en struktur som jeg synes er enklere å bruke med tanke på det som skal vises frem.

2023-09-26 07:52 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/Tabell/TabellVisningMedTag.tsx
> +        <>
```suggestion
```
Fjern tomme react-fragments

2023-09-26 08:17 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/TidligereVedtaksperiodeKort.tsx
> +const StønadsKort: React.FC<{ stonad: IStonader }> = ({ stonad }) => {
enten `StønadKort` eller `Stønadskort`

2023-09-26 08:20 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/typer.ts
> +export interface IStonader {
Navnet `IStonader` tilsier at dette objektet er en liste som inneholder flere objekter av typen `IStonad`, noe som ikke er tilfellet her. Jeg ville renamet til noe annet, men vet ikke om `IStonad` blir helt riktig, for dette objektet er ikke en Stønad. 

Vi har ellers i løsningen også brukt æ, ø og å, så det går forresten helt fint å brukke disse i props og typenavn :)

2023-09-26 08:25 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/typer.ts
> +    verdier?: IVerdier;
er feltet `verdier` nødvendig her? Kunne man bare kalt feltene for `harTidligereStønadISak` og `harTidligereStønadIInfotrygd` og lagt dem på samme nivå som de andre feltene?

2023-09-26 08:29 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/TidligereVedtaksperioder/typer.ts
> +    verdier?: IVerdier;
Generelt vil jeg også si at et felt i et objekt burde få navn basert på hvilken informasjon feltet tilbyr

2023-09-26 08:43 UTC, ma10s approved these changes
Se gjerne på tilbakemeldingene fra Viktor - han hadde noen gode poenger - ellers kjempebra :D

2023-09-27 11:25 UTC, ma10s commented on src/frontend/Komponenter/Behandling/Brev/BrevTyper.ts
> +export const datasett = 'ef-test'; /*TODO bytt tilbake*/
UPS - denne må fikses!

2023-09-27 11:25 UTC, ma10s requested changes
export const datasett = 'ef-test'; /*TODO bytt tilbake*/

2023-09-28 10:38 UTC, ma10s approved these changes

2023-09-28 11:14 UTC, merged