Ønsker å vise infotekst under spørsmål om unntak fra forutgående medl…
navikt/familie-ef-sak-frontend pull request #2526
Opened 2023-09-15 10:33 UTC by gunnsteingarmo

### Hvorfor er denne endringen nødvendig? ✨
Ønsker å vise infotekst under spørsmål om unntak fra forutgående medlemskap, har derfor lagt til en alert av typen info med ønsket tekst.

Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15409

![image](https://github.com/navikt/familie-ef-sak-frontend/assets/141132903/50a99878-66c1-45a8-b4e8-b54522685fa6)

2023-09-21 07:45 UTC, olekvernberg approved these changes

2023-09-21 11:17 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/Vurdering/Delvilkår.tsx
> +                            {delvilkårTypeTilTekst[regel.regelId] === unntakFraHovedregelTekst &&
```suggestion
                            {regel.regelId === 'MEDLEMSKAP_UNNTAK' &&
```
Denne sjekken blir mer presis.

Slik det er gjort nå, så vil infoboksen også dukke opp for unntak for det neste inngangsvilkåret:
![Skjermbilde 2023-09-21 kl  13 16 14](https://github.com/navikt/familie-ef-sak-frontend/assets/32769446/a7ab3647-41f9-4824-8dbc-a9dc3b3348c3)

2023-09-21 11:18 UTC, ViktorGSolberg requested changes
Infoboksen opptrer foreløpig under et annet inngangsvilkår også

2023-09-21 11:29 UTC, ViktorGSolberg commented on src/frontend/Komponenter/Behandling/Vurdering/Delvilkår.tsx
> +                                )}
Et annet tips: Denne logikken blir enklere å følge dersom du drar ut denne infostripen til en egen komponent. Et eksempel:

```suggestion
                              <InfoStripe indeks={i} regelId={regel.regelId} />
```
Også definerer du denne komponenten nederst i fila:

const InfoStripe: FC<{ indeks: number; regelId: string }> = ({ indeks, regelId }) => {
    const skalViseInfostripe = indeks === 0 && regelId === 'MEDLEMSKAP_UNNTAK';

    if (!skalViseInfostripe) {
        return <></>;
    }

    return (
        <Alert size="small" variant="info">
            Det er nye regler for unntak fra 1. september 2023. Du må vurdere om det er nye eller
            gamle regler som gjelder for saken din.
        </Alert>
    );
};

2023-09-26 07:46 UTC, ViktorGSolberg approved these changes
Ser bra ut 

![image](https://github.com/navikt/familie-ef-sak-frontend/assets/32769446/a5ad8318-9ee1-4356-b6e2-741fea0a174b)

2023-09-26 07:49 UTC, merged