Validering av innvilge vedtak
navikt/familie-ef-sak-frontend pull request #346
Opened 2021-06-29 15:28 UTC by alexandraback

2021-06-29 15:41 UTC, blommish commented on src/frontend/hooks/felles/useFormState.ts
> +    }, false);
Kommer denne noen gang returnere true? Initvalue er false og alle if's i denne returnerer `acc && <noe>` => false, eller return false

2021-06-29 21:56 UTC, alexandraback commented on src/frontend/hooks/felles/useFormState.ts
> +    }, false);
nope... så fiksade det hær  [9ff4cd3](https://github.com/navikt/familie-ef-sak-frontend/pull/346/commits/9ff4cd303225e8239f473e47222b8583034b0cb2) ;)

2021-06-30 07:28 UTC, blommish commented
Virker som att `Aktivitet` ikke valideres (sett til `Velg` og beregn)? 
Tekster~ 
![image](https://user-images.githubusercontent.com/937168/123919576-58e1c180-d985-11eb-8425-0af93fc00ee8.png)
![image](https://user-images.githubusercontent.com/937168/123919589-5da67580-d985-11eb-935d-b010b1f5947f.png)

2021-06-30 07:47 UTC, alexandraback commented
Trodde vi var eniga om att vi inte behøver validera aktivitet nær vi ska beregne beløpet ? [pr]( https://github.com/navikt/familie-ef-sak/pull/739)

2021-06-30 09:17 UTC, blommish commented
> Trodde vi var eniga om att vi inte behøver validera aktivitet nær vi ska beregne beløpet ? [pr-ef-sak](https://github.com/navikt/familie-ef-sak/pull/739)

Brukes ikke validering for innsending og da?

2021-07-01 08:24 UTC, Assios requested changes

2021-07-01 08:24 UTC, Assios commented on src/frontend/komponenter/Behandling/VedtakOgBeregning/vedtaksvalidering.ts
> +                    årMånedFra: `Ugyldig periode - fra (${årMånedFra})  må være før til (${årMånedTil})`,
Her er det vel `forrige.årMånedFra` som må være før `årMånedTil`. Feilmeldingen blir feil nå: 
![Skjermbilde 2021-07-01 kl  10 19 08](https://user-images.githubusercontent.com/1413265/124091596-4d120000-da56-11eb-8214-c17718897128.png)

2021-07-01 19:15 UTC, alexandraback commented on src/frontend/komponenter/Behandling/VedtakOgBeregning/vedtaksvalidering.ts
> +                    årMånedFra: `Ugyldig periode - fra (${årMånedFra})  må være før til (${årMånedTil})`,
![Skjermbilde 2021-07-01 kl  21 10 46](https://user-images.githubusercontent.com/10879817/124178058-609e8480-dab1-11eb-8fa3-01ad0e31cbd4.png)
Good catch, fikset!!!

2021-07-02 07:22 UTC, Assios approved these changes
Bra! Én liten kommentar

![image](https://user-images.githubusercontent.com/1413265/124236618-eb659a80-db16-11eb-8e87-f2ac6d6ddc77.png)

2021-07-02 07:22 UTC, Assios commented on src/frontend/komponenter/Behandling/VedtakOgBeregning/vedtaksvalidering.ts
> +                    årMånedFra: `Ugyldig etterfølgende periode - fra (${årMånedFra})må være etter til (${forrige.årMånedTil})`,
mangler bare et mellomrom før "må"

2021-07-02 09:13 UTC, alexandraback commented on src/frontend/komponenter/Behandling/VedtakOgBeregning/vedtaksvalidering.ts
> +                    årMånedFra: `Ugyldig etterfølgende periode - fra (${årMånedFra})må være etter til (${forrige.årMånedTil})`,
fikset!

2021-07-02 09:13 UTC, merged