Fjern duplikater av flettefelt i brevmeny
navikt/familie-ef-sak-frontend pull request #451
Opened 2021-08-30 12:11 UTC by Assios

Løser [denne oppgaven](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-6014).

2021-08-30 12:35 UTC, charliemidtlyng commented on src/frontend/Komponenter/Behandling/Brev/BrevMenyDelmal.tsx
> +                                index === self.findIndex((t) => t._ref === felt._ref)
Aldri lett å lese, men antar at denne finner første treff med samme referanse og følgelig filtrerer bort treff #2, #3... #n i lista?

2021-08-30 12:35 UTC, charliemidtlyng approved these changes

2021-08-31 10:52 UTC, eirarset requested changes
Ser bra ut, men tror også vi vil gjøre den samme filtreringen i `<FlettefelterForValgtFelt />`

Og klarer vi evt. håndtere at et flettefelt ikke kommer med både i `<BrevMenyDelmal />` og `<FlettefelterForValgtFelt />`. Jeg kommer ikke umiddelbart på noen god løsning, men hadde vært kult å få til.

2021-09-01 07:31 UTC, Assios commented on src/frontend/Komponenter/Behandling/Brev/BrevMenyDelmal.tsx
> +                                index === self.findIndex((t) => t._ref === felt._ref)
Jepp, det stemmer.

2021-09-01 10:37 UTC, Assios commented
> Ser bra ut, men tror også vi vil gjøre den samme filtreringen i `<FlettefelterForValgtFelt />`
> 
> Og klarer vi evt. håndtere at et flettefelt ikke kommer med både i `<BrevMenyDelmal />` og `<FlettefelterForValgtFelt />`. Jeg kommer ikke umiddelbart på noen god løsning, men hadde vært kult å få til.

La det til i ValgfeltSelect nå, fd4f1d5

2021-09-01 11:17 UTC, eirarset approved these changes

2021-09-01 13:03 UTC, merged